### ISSUE TITLE
Broken links one homepage

### ISSUE THREAD

**Issue by fingolfin** [peal/vole#19]
On https://peal.github.io/vole/  there broken links giving 404 errors:
- https://gap-packages.github.io/QuickCheck/
- https://markuspf.github.io/OrbitalGraphs/

So I went to look for the repos but <https://github.com/gap-packages/QuickCheck> does not exist! But @ChrisJefferson tells me it is https://github.com/ChrisJefferson/QuickCheck

OTOH https://github.com/markuspf/OrbitalGraphs does exist but it seems to be an outdated version of https://github.com/gap-packages/OrbitalGraphs -- that repository apparently has an outdated `PackageInfo.g` with the old URLs listed?

Both packages probably simply need a release?

**Comment by wilfwilson** [comment]
Thanks @fingolfin.

Yes, those URLs are derived from the PackageInfo.g files of the versions of the packages that I have installed on my computer.

I was aware of the problem with QuickCheck, and I have a PR to @ChrisJefferson's repo to fix it: https://github.com/ChrisJefferson/QuickCheck/pull/3

I didn't know about the problem with OrbitalGraphs, so thanks again for that, but I just fixed it now in https://github.com/gap-packages/OrbitalGraphs/commit/3d4459283cf6d8a566fce3366eba9ec35a77de2c.

I think neither package has had an actual release yet, which is fine for now I think. It's fine for just their master branches to be fixed.

I rebuilt the website with my fixed versions of these packages so I'll close the issue.
