### ISSUE TITLE
Missing ForceQuitGap

### ISSUE THREAD

**Issue by MathieuDutSik** [peal/vole#71]
The "ForceQuitGap" appears missing in the code and I have a warning.
```
Syntax warning: Unbound global variable in /Users/mathieu/opt/gap-4.11.1/pkg/vole/gap/internal/comms.gi:248
        ForceQuitGap();
```
This does not prevent vole from loading though.

**Comment by wilfwilson** [comment]
Thank you for creating this issue, `ForceQuitGap` is only available in GAP 4.12, which we hadn't realised.
