### ISSUE TITLE
Rename `dependancies` to `dependencies` in the package

### ISSUE THREAD

**Issue by wilfwilson** [peal/vole#79]
@ChrisJefferson would you please rename `dependancies` to `dependencies` throughout the package (i.e. fix the spelling of the new directory that you made)?

I assume you're still actively working on this stuff, so I don't want to do something that'll conflict with whatever you're up to 🙂

**Comment by ChrisJefferson** [comment]
Done :)

**Comment by wilfwilson** [comment]
Cheers
